### ISSUE TITLE
rspec testsuite failure with ruby 3.4.0dev

### ISSUE THREAD

**Issue by mtasaka** [egonSchiele/contracts.ruby#309] opened 2024-11-26 06:52 UTC
Trying with `ruby 3.4.0dev (2024-11-26 master 7be0d50514) +PRISM [x86_64-linux]` :
https://github.com/ruby/ruby/commit/7be0d505146deb4a8a641da3b1c0e4d2aa174784

contracts.ruby git head ( https://github.com/egonSchiele/contracts.ruby/commit/8329024bc87f1aa018a58d84b2775d23632fc716 )
rspec testsuite fails like:

```
$ rspec
Run options: include {focus: true}

All examples were filtered out; ignoring {focus: true}

Randomized with seed 48063
..................................................................................................................................................F...................................................................................................

Failures:

  1) Contracts: Required named arguments really complicated method signature should fail when passed nil to an optional argument which contract shouldn't accept nil
     Failure/Error:
       expect do
         @o.complicated("a", true, :b, :c, 2.0, e: (1..5), f: nil, g: :d) do |x|
           x
         end
       end.to raise_error(ContractError, /Expected: \(KeywordArgs\[{:e=>Range, :f=>Optional\[Num\], :g=>Symbol}\]\)/)
     
       expected ContractError with message matching /Expected: \(KeywordArgs\[{:e=>Range, :f=>Optional\[Num\], :g=>Symbol}\]\)/, got #<ParamContractError:"Contract violation for argument keyword of 6:\n        Expected: (KeywordArgs[{...n        At: /builddir/build/GIT/contracts.ruby/spec/ruby_version_specific/contracts_spec_2.1.rb:4"> with backtrace:
         # ./lib/contracts.rb:52:in 'block in <class:Contract>'
         # ./lib/contracts.rb:193:in 'Contract.failure_callback'
         # ./lib/contracts/method_handler.rb:144:in 'block in GenericExample#redefine_method'
         # ./spec/ruby_version_specific/contracts_spec_2.1.rb:56:in 'block (5 levels) in <top (required)>'
         # ./spec/ruby_version_specific/contracts_spec_2.1.rb:59:in 'block (4 levels) in <top (required)>'
     # ./spec/ruby_version_specific/contracts_spec_2.1.rb:59:in 'block (4 levels) in <top (required)>'


Finished in 0.24538 seconds (files took 0.18469 seconds to load)
246 examples, 1 failure

```

**Comment by PikachuEXE** [comment] 2024-11-27 01:03
Reproduced with 3.4.0-preview2, investigating~

**Comment by PikachuEXE** [comment] 2024-11-27 01:19
New error message is now
```
Contract violation for argument keyword of 6:
        Expected: (KeywordArgs[{e: Range, f: Optional[Num], g: Symbol}]),
        Actual: {e: 1..5, f: nil, g: :d}
        Value guarded in: GenericExample::complicated
        With Contract: String, Bool, Args, Float, Proc => Array
```
and
```ruby
"Expected: (KeywordArgs[{e: Range, f: Optional[Num], g: Symbol}])".match?(/Expected: \(KeywordArgs\[{:e=>Range, :f=>Optional\[Num\], :g=>Symbol}\]\)/) #=> false
```

Since the later message use `key: value` instead of `:key => value` =_=
Thanks for reporting this should be fixed soon :P

**Comment by PikachuEXE** [comment] 2024-11-27 01:53
Fixed in latest commits but cucumber or ruby got issue on
https://github.com/cucumber/cucumber-ruby/blob/v9.2.0/lib/cucumber/multiline_argument/data_table.rb#L78
Which can be reproduced with `Hash.new(strict: false).freeze`

But that's not something we can fix

**Closed by PikachuEXE** 2024-11-27 01:53 UTC
